#!/usr/bin/env python
# -*- coding:utf-8 -*-
import sys
import difflib

output = sys.argv[1]
answer = sys.argv[2]
with open(output) as f:
    output_f = f.readlines()

with open(answer) as f:
    answer_f = f.readlines()

o = []
for i in output_f:
    o.append(i.rstrip("\n").rstrip(" "))
output_f = o
o = []

for i in answer_f:
    o.append(i.rstrip("\n").rstrip(" "))
answer_f = o
o = []

while len(output_f) > 0 and output_f[-1] == '':
    del output_f[-1]

while len(answer_f) > 0 and answer_f[-1] == '':
    del answer_f[-1]

if len(output_f) != len(answer_f):
    sys.stdout.writelines(difflib.unified_diff([i + '\n' for i in answer_f], [i + '\n' for i in output_f], fromfile='answer', tofile='output'))
    exit(1)

if output_f == answer_f:
    exit(0)

pe_lines = -1
for i in range(len(output_f)):
    if output_f[i] != answer_f[i]:
        if output_f[i].replace(" ", "").replace("\n", "") == answer_f[i].replace(" ", "").replace("\n", ""):
            pe_lines = i
            break
        else:
            sys.stdout.writelines(difflib.unified_diff([i + '\n' for i in answer_f], [i + '\n' for i in output_f], fromfile='answer', tofile='output'))
            exit(1)
print("### 第{}行格式错误。".format(pe_lines))
exit(2)

