#!/usr/bin/env python
# -*- coding:utf-8 -*-
import sys
import difflib


output = sys.argv[1]
answer = sys.argv[2]
with open(output) as f:
    output_f = f.readlines()

with open(answer) as f:
    answer_f = f.readlines()


def wa():
    sys.stdout.writelines(difflib.unified_diff(answer_f, output_f, fromfile='answer', tofile='output'))
    exit(1)

if len((" ".join([i.strip() for i in output_f])).split(" ")) != len(" ".join([i.strip() for i in answer_f]).split(" ")):
    wa()

output_s = (" ".join([i.strip() for i in output_f])).split(" ")
answer_s = (" ".join([i.strip() for i in answer_f])).split(" ")

try:
    for i in range(0, len(answer_s)):
        if abs(float(output_s[i]) - float(answer_s[i])) > 1e-8:
            wa()
except Exception:
    wa()

exit(0)
