on: [push, pull_request]
name: Coverage
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Install Lib Seccomp
        run: sudo apt-get install libseccomp-dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Go Test
        run: sudo go test ./... -race -coverprofile=coverage.txt -covermode=atomic
        continue-on-error: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
